sudo: false
language: java

jdk:
- oraclejdk8

services:
- docker

env:
  REPO: slawekm/openregister-loader

cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper

script:
- ./gradlew clean build

after_success:
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TRAVIS_BRANCH
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $REPO
