sudo: required
language: java

jdk:
- oraclejdk8

services:
- docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPOSITORY=openregister/loader

cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper

script:
- ./gradlew clean build
- docker build -t $REPOSITORY:$COMMIT .
- docker tag $REPOSITORY:$COMMIT $REPOSITORY:$TRAVIS_BRANCH
- docker tag $REPOSITORY:$COMMIT $REPOSITORY:travis-$TRAVIS_BUILD_NUMBER
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $REPOSITORY
