sudo: false
language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
before_install:
script:
- ./gradlew clean build
- docker build -t openregister/loader .
