sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
before_install:
- docker pull alpine:latest
script:
- ./gradlew clean build
